# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/peo/Curious/Visual/deconv/deconv_open

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/peo/Curious/Visual/deconv/deconv_open

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/peo/Curious/Visual/deconv/deconv_open/CMakeFiles /media/peo/Curious/Visual/deconv/deconv_open/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/peo/Curious/Visual/deconv/deconv_open/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psf2Ddemo

# Build rule for target.
psf2Ddemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psf2Ddemo
.PHONY : psf2Ddemo

# fast build rule for target.
psf2Ddemo/fast:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/build
.PHONY : psf2Ddemo/fast

#=============================================================================
# Target rules for targets named psfSpeed

# Build rule for target.
psfSpeed: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psfSpeed
.PHONY : psfSpeed

# fast build rule for target.
psfSpeed/fast:
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/build
.PHONY : psfSpeed/fast

#=============================================================================
# Target rules for targets named deconvLucyDemo

# Build rule for target.
deconvLucyDemo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 deconvLucyDemo
.PHONY : deconvLucyDemo

# fast build rule for target.
deconvLucyDemo/fast:
	$(MAKE) -f CMakeFiles/deconvLucyDemo.dir/build.make CMakeFiles/deconvLucyDemo.dir/build
.PHONY : deconvLucyDemo/fast

src/cvTools.o: src/cvTools.cpp.o

.PHONY : src/cvTools.o

# target to build an object file
src/cvTools.cpp.o:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/cvTools.cpp.o
.PHONY : src/cvTools.cpp.o

src/cvTools.i: src/cvTools.cpp.i

.PHONY : src/cvTools.i

# target to preprocess a source file
src/cvTools.cpp.i:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/cvTools.cpp.i
.PHONY : src/cvTools.cpp.i

src/cvTools.s: src/cvTools.cpp.s

.PHONY : src/cvTools.s

# target to generate assembly for a file
src/cvTools.cpp.s:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/cvTools.cpp.s
.PHONY : src/cvTools.cpp.s

src/demo_deconv_LR.o: src/demo_deconv_LR.cpp.o

.PHONY : src/demo_deconv_LR.o

# target to build an object file
src/demo_deconv_LR.cpp.o:
	$(MAKE) -f CMakeFiles/deconvLucyDemo.dir/build.make CMakeFiles/deconvLucyDemo.dir/src/demo_deconv_LR.cpp.o
.PHONY : src/demo_deconv_LR.cpp.o

src/demo_deconv_LR.i: src/demo_deconv_LR.cpp.i

.PHONY : src/demo_deconv_LR.i

# target to preprocess a source file
src/demo_deconv_LR.cpp.i:
	$(MAKE) -f CMakeFiles/deconvLucyDemo.dir/build.make CMakeFiles/deconvLucyDemo.dir/src/demo_deconv_LR.cpp.i
.PHONY : src/demo_deconv_LR.cpp.i

src/demo_deconv_LR.s: src/demo_deconv_LR.cpp.s

.PHONY : src/demo_deconv_LR.s

# target to generate assembly for a file
src/demo_deconv_LR.cpp.s:
	$(MAKE) -f CMakeFiles/deconvLucyDemo.dir/build.make CMakeFiles/deconvLucyDemo.dir/src/demo_deconv_LR.cpp.s
.PHONY : src/demo_deconv_LR.cpp.s

src/psf_accelerate.o: src/psf_accelerate.cpp.o

.PHONY : src/psf_accelerate.o

# target to build an object file
src/psf_accelerate.cpp.o:
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/src/psf_accelerate.cpp.o
.PHONY : src/psf_accelerate.cpp.o

src/psf_accelerate.i: src/psf_accelerate.cpp.i

.PHONY : src/psf_accelerate.i

# target to preprocess a source file
src/psf_accelerate.cpp.i:
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/src/psf_accelerate.cpp.i
.PHONY : src/psf_accelerate.cpp.i

src/psf_accelerate.s: src/psf_accelerate.cpp.s

.PHONY : src/psf_accelerate.s

# target to generate assembly for a file
src/psf_accelerate.cpp.s:
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/src/psf_accelerate.cpp.s
.PHONY : src/psf_accelerate.cpp.s

src/psf_gen2.o: src/psf_gen2.cpp.o

.PHONY : src/psf_gen2.o

# target to build an object file
src/psf_gen2.cpp.o:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/psf_gen2.cpp.o
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/src/psf_gen2.cpp.o
.PHONY : src/psf_gen2.cpp.o

src/psf_gen2.i: src/psf_gen2.cpp.i

.PHONY : src/psf_gen2.i

# target to preprocess a source file
src/psf_gen2.cpp.i:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/psf_gen2.cpp.i
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/src/psf_gen2.cpp.i
.PHONY : src/psf_gen2.cpp.i

src/psf_gen2.s: src/psf_gen2.cpp.s

.PHONY : src/psf_gen2.s

# target to generate assembly for a file
src/psf_gen2.cpp.s:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/psf_gen2.cpp.s
	$(MAKE) -f CMakeFiles/psfSpeed.dir/build.make CMakeFiles/psfSpeed.dir/src/psf_gen2.cpp.s
.PHONY : src/psf_gen2.cpp.s

src/psfg.o: src/psfg.cpp.o

.PHONY : src/psfg.o

# target to build an object file
src/psfg.cpp.o:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/psfg.cpp.o
.PHONY : src/psfg.cpp.o

src/psfg.i: src/psfg.cpp.i

.PHONY : src/psfg.i

# target to preprocess a source file
src/psfg.cpp.i:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/psfg.cpp.i
.PHONY : src/psfg.cpp.i

src/psfg.s: src/psfg.cpp.s

.PHONY : src/psfg.s

# target to generate assembly for a file
src/psfg.cpp.s:
	$(MAKE) -f CMakeFiles/psf2Ddemo.dir/build.make CMakeFiles/psf2Ddemo.dir/src/psfg.cpp.s
.PHONY : src/psfg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... psf2Ddemo"
	@echo "... psfSpeed"
	@echo "... rebuild_cache"
	@echo "... deconvLucyDemo"
	@echo "... src/cvTools.o"
	@echo "... src/cvTools.i"
	@echo "... src/cvTools.s"
	@echo "... src/demo_deconv_LR.o"
	@echo "... src/demo_deconv_LR.i"
	@echo "... src/demo_deconv_LR.s"
	@echo "... src/psf_accelerate.o"
	@echo "... src/psf_accelerate.i"
	@echo "... src/psf_accelerate.s"
	@echo "... src/psf_gen2.o"
	@echo "... src/psf_gen2.i"
	@echo "... src/psf_gen2.s"
	@echo "... src/psfg.o"
	@echo "... src/psfg.i"
	@echo "... src/psfg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

