# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.8

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/peo/Downloads/clion-2017.1.3/bin/cmake/bin/cmake

# The command to remove a file.
RM = /home/peo/Downloads/clion-2017.1.3/bin/cmake/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /media/peo/Curious/Visual/deconv/deconv_open

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /media/peo/Curious/Visual/deconv/deconv_open

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/peo/Downloads/clion-2017.1.3/bin/cmake/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/peo/Downloads/clion-2017.1.3/bin/cmake/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /media/peo/Curious/Visual/deconv/deconv_open/CMakeFiles /media/peo/Curious/Visual/deconv/deconv_open/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /media/peo/Curious/Visual/deconv/deconv_open/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named psf

# Build rule for target.
psf: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 psf
.PHONY : psf

# fast build rule for target.
psf/fast:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/build
.PHONY : psf/fast

src/comparemat.o: src/comparemat.cpp.o

.PHONY : src/comparemat.o

# target to build an object file
src/comparemat.cpp.o:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/comparemat.cpp.o
.PHONY : src/comparemat.cpp.o

src/comparemat.i: src/comparemat.cpp.i

.PHONY : src/comparemat.i

# target to preprocess a source file
src/comparemat.cpp.i:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/comparemat.cpp.i
.PHONY : src/comparemat.cpp.i

src/comparemat.s: src/comparemat.cpp.s

.PHONY : src/comparemat.s

# target to generate assembly for a file
src/comparemat.cpp.s:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/comparemat.cpp.s
.PHONY : src/comparemat.cpp.s

src/cvutils.o: src/cvutils.cpp.o

.PHONY : src/cvutils.o

# target to build an object file
src/cvutils.cpp.o:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/cvutils.cpp.o
.PHONY : src/cvutils.cpp.o

src/cvutils.i: src/cvutils.cpp.i

.PHONY : src/cvutils.i

# target to preprocess a source file
src/cvutils.cpp.i:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/cvutils.cpp.i
.PHONY : src/cvutils.cpp.i

src/cvutils.s: src/cvutils.cpp.s

.PHONY : src/cvutils.s

# target to generate assembly for a file
src/cvutils.cpp.s:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/cvutils.cpp.s
.PHONY : src/cvutils.cpp.s

src/deconvpsf.o: src/deconvpsf.cpp.o

.PHONY : src/deconvpsf.o

# target to build an object file
src/deconvpsf.cpp.o:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/deconvpsf.cpp.o
.PHONY : src/deconvpsf.cpp.o

src/deconvpsf.i: src/deconvpsf.cpp.i

.PHONY : src/deconvpsf.i

# target to preprocess a source file
src/deconvpsf.cpp.i:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/deconvpsf.cpp.i
.PHONY : src/deconvpsf.cpp.i

src/deconvpsf.s: src/deconvpsf.cpp.s

.PHONY : src/deconvpsf.s

# target to generate assembly for a file
src/deconvpsf.cpp.s:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/deconvpsf.cpp.s
.PHONY : src/deconvpsf.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/psf_gen2.o: src/psf_gen2.cpp.o

.PHONY : src/psf_gen2.o

# target to build an object file
src/psf_gen2.cpp.o:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/psf_gen2.cpp.o
.PHONY : src/psf_gen2.cpp.o

src/psf_gen2.i: src/psf_gen2.cpp.i

.PHONY : src/psf_gen2.i

# target to preprocess a source file
src/psf_gen2.cpp.i:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/psf_gen2.cpp.i
.PHONY : src/psf_gen2.cpp.i

src/psf_gen2.s: src/psf_gen2.cpp.s

.PHONY : src/psf_gen2.s

# target to generate assembly for a file
src/psf_gen2.cpp.s:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/psf_gen2.cpp.s
.PHONY : src/psf_gen2.cpp.s

src/vtkutils.o: src/vtkutils.cpp.o

.PHONY : src/vtkutils.o

# target to build an object file
src/vtkutils.cpp.o:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/vtkutils.cpp.o
.PHONY : src/vtkutils.cpp.o

src/vtkutils.i: src/vtkutils.cpp.i

.PHONY : src/vtkutils.i

# target to preprocess a source file
src/vtkutils.cpp.i:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/vtkutils.cpp.i
.PHONY : src/vtkutils.cpp.i

src/vtkutils.s: src/vtkutils.cpp.s

.PHONY : src/vtkutils.s

# target to generate assembly for a file
src/vtkutils.cpp.s:
	$(MAKE) -f CMakeFiles/psf.dir/build.make CMakeFiles/psf.dir/src/vtkutils.cpp.s
.PHONY : src/vtkutils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... psf"
	@echo "... src/comparemat.o"
	@echo "... src/comparemat.i"
	@echo "... src/comparemat.s"
	@echo "... src/cvutils.o"
	@echo "... src/cvutils.i"
	@echo "... src/cvutils.s"
	@echo "... src/deconvpsf.o"
	@echo "... src/deconvpsf.i"
	@echo "... src/deconvpsf.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/psf_gen2.o"
	@echo "... src/psf_gen2.i"
	@echo "... src/psf_gen2.s"
	@echo "... src/vtkutils.o"
	@echo "... src/vtkutils.i"
	@echo "... src/vtkutils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

